"""Design tokens as CSS variables, Tailwind (v3 and v4), SCSS and W3C design-token JSON."""

from __future__ import annotations

import json
from typing import Any

from code_ai.tools.design.tokens import DesignSystem

FORMATS = ("css", "tailwind3", "tailwind4", "scss", "json", "styleguide")
FILENAMES = {
    "css": "tokens.css",
    "tailwind3": "tailwind.config.js",
    "tailwind4": "theme.css",
    "scss": "_tokens.scss",
    "json": "tokens.json",
    "styleguide": "styleguide.html",
}


def _flat_static(ds: DesignSystem, prefix: str) -> list[tuple[str, str]]:
    rows: list[tuple[str, str]] = []
    for group, scale in ds.colors.items():
        rows += [(f"--{prefix}color-{group}-{step}", value) for step, value in scale.items()]
    for key, spec in ds.typography["sizes"].items():
        rows.append((f"--{prefix}font-size-{key}", spec["fluid"]))
        rows.append((f"--{prefix}line-height-{key}", spec["line-height"]))
        rows.append((f"--{prefix}letter-spacing-{key}", spec["letter-spacing"]))
    rows += [(f"--{prefix}font-weight-{k}", str(v)) for k, v in ds.typography["weights"].items()]
    rows += [(f"--{prefix}font-{k}", v) for k, v in ds.fonts.items()]
    rows += [(f"--{prefix}space-{k}", v) for k, v in ds.spacing.items()]
    rows += [(f"--{prefix}radius-{k}", v) for k, v in ds.radii.items()]
    rows += [(f"--{prefix}shadow-{k}", v) for k, v in ds.shadows.items()]
    rows += [(f"--{prefix}z-{k}", str(v)) for k, v in ds.z_index.items()]
    rows += [(f"--{prefix}{k}", v) for k, v in ds.motion.items()]
    rows += [(f"--{prefix}breakpoint-{k}", v) for k, v in ds.breakpoints.items()]
    return rows


def _roles(roles: dict[str, str], prefix: str, indent: str = "  ") -> str:
    return "\n".join(f"{indent}--{prefix}{name}: {value};" for name, value in roles.items())


def css(ds: DesignSystem, prefix: str = "") -> str:
    static = "\n".join(f"  {name}: {value};" for name, value in _flat_static(ds, prefix))
    return f"""/* Design tokens: {ds.name}. Generated by Code-AI. */
:root {{
{static}
}}

/* Light theme (default) */
:root,
[data-theme="light"] {{
  color-scheme: light;
{_roles(ds.themes["light"], prefix)}
}}

/* Dark theme: follows the OS unless a data-theme attribute says otherwise */
@media (prefers-color-scheme: dark) {{
  :root:not([data-theme="light"]) {{
    color-scheme: dark;
{_roles(ds.themes["dark"], prefix, "    ")}
  }}
}}

[data-theme="dark"] {{
  color-scheme: dark;
{_roles(ds.themes["dark"], prefix)}
}}

@media (prefers-reduced-motion: reduce) {{
  :root {{
    --{prefix}duration-fast: 0ms;
    --{prefix}duration-base: 0ms;
    --{prefix}duration-slow: 0ms;
  }}
}}
"""


def tailwind3(ds: DesignSystem, prefix: str = "") -> str:
    colors: dict[str, Any] = {
        group: {str(k): v for k, v in scale.items()} for group, scale in ds.colors.items()
    }
    for role in ds.themes["light"]:
        colors[role] = f"var(--{prefix}{role})"
    config = {
        "darkMode": ["class", '[data-theme="dark"]'],
        "theme": {
            "extend": {
                "colors": colors,
                "fontFamily": {k: [v] for k, v in ds.fonts.items()},
                "fontSize": {
                    k: [
                        spec["fluid"],
                        {
                            "lineHeight": spec["line-height"],
                            "letterSpacing": spec["letter-spacing"],
                        },
                    ]
                    for k, spec in ds.typography["sizes"].items()
                },
                "spacing": {k.replace("_", "."): v for k, v in ds.spacing.items()},
                "borderRadius": ds.radii,
                "boxShadow": ds.shadows,
                "screens": ds.breakpoints,
                "zIndex": {k: str(v) for k, v in ds.z_index.items()},
                "transitionDuration": {
                    k.split("-", 1)[1]: v for k, v in ds.motion.items() if k.startswith("duration")
                },
                "transitionTimingFunction": {
                    k.split("-", 1)[1]: v for k, v in ds.motion.items() if k.startswith("ease")
                },
            }
        },
    }
    body = json.dumps(config, indent=2)
    return (
        f"// Tailwind CSS v3 config for {ds.name}. Load tokens.css for the themed role colours.\n"
        f"/** @type {{import('tailwindcss').Config}} */\nmodule.exports = {body};\n"
    )


def tailwind4(ds: DesignSystem, prefix: str = "") -> str:
    lines = [
        f"/* Tailwind CSS v4 theme for {ds.name}. */",
        '@import "tailwindcss";',
        "",
        "@theme {",
    ]
    for group, scale in ds.colors.items():
        lines += [f"  --color-{group}-{step}: {value};" for step, value in scale.items()]
    for role, value in ds.themes["light"].items():
        lines.append(f"  --color-{role}: {value};")
    lines += [f"  --font-{k}: {v};" for k, v in ds.fonts.items()]
    for key, spec in ds.typography["sizes"].items():
        lines.append(f"  --text-{key}: {spec['fluid']};")
        lines.append(f"  --text-{key}--line-height: {spec['line-height']};")
    lines += [f"  --radius-{k}: {v};" for k, v in ds.radii.items() if k != "none"]
    lines += [f"  --shadow-{k}: {v};" for k, v in ds.shadows.items()]
    lines += [f"  --breakpoint-{k}: {v};" for k, v in ds.breakpoints.items()]
    lines.append(f"  --spacing: {ds.spacing['1']};")
    lines.append("}")
    lines += ["", "@layer base {", '  [data-theme="dark"] {']
    lines += [f"    --color-{role}: {value};" for role, value in ds.themes["dark"].items()]
    lines += ["  }", "}", ""]
    return "\n".join(lines)


def scss(ds: DesignSystem, prefix: str = "") -> str:
    lines = [f"// SCSS tokens for {ds.name}."]
    for name, value in _flat_static(ds, prefix):
        lines.append(f"${name[2:]}: {value};")
    for theme, roles in ds.themes.items():
        lines.append(f"${prefix}theme-{theme}: (")
        lines += [f'  "{role}": {value},' for role, value in roles.items()]
        lines.append(");")
    return "\n".join(lines) + "\n"


def w3c_json(ds: DesignSystem) -> str:
    def token(value, kind):
        return {"$value": value, "$type": kind}

    data: dict[str, Any] = {
        "color": {
            group: {str(step): token(value, "color") for step, value in scale.items()}
            for group, scale in ds.colors.items()
        },
        "theme": {
            name: {role: token(value, "color") for role, value in roles.items()}
            for name, roles in ds.themes.items()
        },
        "font": {
            "family": {k: token(v, "fontFamily") for k, v in ds.fonts.items()},
            "size": {
                k: token(spec["size"], "dimension") for k, spec in ds.typography["sizes"].items()
            },
            "weight": {k: token(v, "fontWeight") for k, v in ds.typography["weights"].items()},
        },
        "space": {k: token(v, "dimension") for k, v in ds.spacing.items()},
        "radius": {k: token(v, "dimension") for k, v in ds.radii.items()},
        "shadow": {k: token(v, "shadow") for k, v in ds.shadows.items()},
        "breakpoint": {k: token(v, "dimension") for k, v in ds.breakpoints.items()},
        "duration": {
            k: token(v, "duration") for k, v in ds.motion.items() if k.startswith("duration")
        },
        "easing": {
            k: token(v, "cubicBezier") for k, v in ds.motion.items() if k.startswith("ease")
        },
    }
    return json.dumps(data, indent=2) + "\n"


def render(ds: DesignSystem, fmt: str, prefix: str = "") -> str:
    if fmt == "css":
        return css(ds, prefix)
    if fmt == "tailwind3":
        return tailwind3(ds, prefix)
    if fmt == "tailwind4":
        return tailwind4(ds, prefix)
    if fmt == "scss":
        return scss(ds, prefix)
    if fmt == "json":
        return w3c_json(ds)
    if fmt == "styleguide":
        from code_ai.tools.design.styleguide import styleguide

        return styleguide(ds, css(ds, ""))
    raise ValueError(fmt)
