"""Article preambles and front matter for each supported class."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from code_ai.core.errors import ToolArgumentError
from code_ai.tools.latex.markup import escape

TEMPLATES = ("article", "ieee", "acm", "springer", "elsevier", "abnt", "report")

# Separators kept out of f-string expressions, where backslashes need Python 3.12.
AND = " \\and "
SEP = " \\sep "


def _keywords(spec: ArticleSpec, separator: str) -> str:
    return separator.join(escape(keyword) for keyword in spec.keywords)


@dataclass
class Author:
    name: str
    affiliation: str = ""
    email: str = ""
    orcid: str = ""


@dataclass
class ArticleSpec:
    template: str
    title: str
    authors: list[Author]
    abstract: str = ""
    abstract_en: str = ""
    keywords: list[str] = field(default_factory=list)
    keywords_en: list[str] = field(default_factory=list)
    body: str = ""
    acknowledgments: str = ""
    appendix: str = ""
    language: str = "english"
    engine: str = "pdflatex"
    has_bibliography: bool = False
    abnt: dict[str, Any] = field(default_factory=dict)
    date: str = ""

    @property
    def portuguese(self) -> bool:
        return self.language.lower().startswith(("pt", "port", "brazil"))


def heading_commands(template: str) -> tuple[str, ...]:
    if template in {"abnt", "report"}:
        return ("chapter", "section", "subsection", "subsubsection")
    return ("section", "subsection", "subsubsection", "paragraph")


def cite_command(template: str) -> str:
    return "cite"


def _babel(spec: ArticleSpec) -> str:
    return "brazilian" if spec.portuguese else "english"


def _encoding(spec: ArticleSpec) -> str:
    if spec.engine in {"xelatex", "lualatex"}:
        return "\\usepackage{fontspec}\n"
    return "\\usepackage[T1]{fontenc}\n\\usepackage[utf8]{inputenc}\n\\usepackage{lmodern}\n"


_COMMON = (
    "\\usepackage{amsmath,amssymb}\n"
    "\\usepackage{graphicx}\n"
    "\\usepackage{booktabs}\n"
    "\\usepackage{xcolor}\n"
)


def _hyperref(spec: ArticleSpec) -> str:
    return (
        "\\usepackage[hidelinks]{hyperref}\n"
        f"\\hypersetup{{pdftitle={{{escape(spec.title)}}}, "
        f"pdfauthor={{{escape(', '.join(a.name for a in spec.authors))}}}}}\n"
    )


def render(spec: ArticleSpec, body: str, appendix: str, bibliography_file: str) -> str:
    if spec.template not in TEMPLATES:
        raise ToolArgumentError(f"template is one of {', '.join(TEMPLATES)}.")
    return {
        "article": _article,
        "report": _report,
        "ieee": _ieee,
        "acm": _acm,
        "springer": _springer,
        "elsevier": _elsevier,
        "abnt": _abnt,
    }[spec.template](spec, body, appendix, bibliography_file)


def _magic(spec: ArticleSpec) -> str:
    return f"% !TEX program = {spec.engine}\n% Generated by Code-AI; edit freely.\n"


def _keywords_line(spec: ArticleSpec) -> str:
    if not spec.keywords:
        return ""
    label = "Palavras-chave" if spec.portuguese else "Keywords"
    return f"\n\\noindent\\textbf{{{label}:}} {escape('; '.join(spec.keywords))}.\n"


def _ack(spec: ArticleSpec, command: str = "section*") -> str:
    if not spec.acknowledgments:
        return ""
    title = "Agradecimentos" if spec.portuguese else "Acknowledgments"
    return f"\n\\{command}{{{title}}}\n{spec.acknowledgments}\n"


def _appendix(appendix: str) -> str:
    return f"\n\\appendix\n{appendix}\n" if appendix.strip() else ""


def _bib(spec: ArticleSpec, style: str, file: str) -> str:
    if not spec.has_bibliography:
        return ""
    return f"\n\\bibliographystyle{{{style}}}\n\\bibliography{{{file}}}\n"


def _article(spec: ArticleSpec, body: str, appendix: str, bib: str) -> str:
    authors = " \\and\n  ".join(
        escape(a.name)
        + (f"\\\\ {escape(a.affiliation)}" if a.affiliation else "")
        + (f"\\\\ \\href{{mailto:{a.email}}}{{\\texttt{{{escape(a.email)}}}}}" if a.email else "")
        for a in spec.authors
    )
    abstract = (
        f"\\begin{{abstract}}\n{spec.abstract}\n{_keywords_line(spec)}\\end{{abstract}}\n"
        if spec.abstract
        else ""
    )
    return (
        _magic(spec)
        + "\\documentclass[11pt,a4paper]{article}\n"
        + _encoding(spec)
        + f"\\usepackage[{_babel(spec)}]{{babel}}\n"
        + "\\usepackage[margin=2.5cm]{geometry}\n"
        + "\\usepackage{microtype}\n"
        + _COMMON
        + "\\usepackage{caption}\n"
        + "\\usepackage[numbers,sort&compress]{natbib}\n"
        + _hyperref(spec)
        + f"\n\\title{{{escape(spec.title)}}}\n\\author{{{authors}}}\n"
        + f"\\date{{{escape(spec.date)}}}\n\n"
        + "\\begin{document}\n\\maketitle\n\n"
        + abstract
        + "\n"
        + body
        + _ack(spec)
        + _bib(spec, "plainnat", bib)
        + _appendix(appendix)
        + "\n\\end{document}\n"
    )


def _report(spec: ArticleSpec, body: str, appendix: str, bib: str) -> str:
    text = _article(spec, body, appendix, bib)
    text = text.replace(
        "\\documentclass[11pt,a4paper]{article}", "\\documentclass[12pt,a4paper,oneside]{report}"
    )
    return text.replace("\\maketitle\n\n", "\\maketitle\n\\tableofcontents\n\n")


def _ieee(spec: ArticleSpec, body: str, appendix: str, bib: str) -> str:
    blocks = "\n\\and\n".join(
        f"\\IEEEauthorblockN{{{escape(a.name)}}}\n\\IEEEauthorblockA{{{escape(a.affiliation)}"
        + (f"\\\\\n{escape(a.email)}" if a.email else "")
        + "}"
        for a in spec.authors
    )
    keywords = (
        f"\\begin{{IEEEkeywords}}\n{escape(', '.join(spec.keywords))}\n\\end{{IEEEkeywords}}\n"
        if spec.keywords
        else ""
    )
    return (
        _magic(spec)
        + "\\documentclass[conference]{IEEEtran}\n"
        + _encoding(spec)
        + f"\\usepackage[{_babel(spec)}]{{babel}}\n"
        + "\\usepackage{cite}\n"
        + _COMMON
        + "\\usepackage{url}\n"
        + _hyperref(spec)
        + f"\n\\title{{{escape(spec.title)}}}\n\\author{{{blocks}}}\n\n"
        + "\\begin{document}\n\\maketitle\n\n"
        + (f"\\begin{{abstract}}\n{spec.abstract}\n\\end{{abstract}}\n" if spec.abstract else "")
        + keywords
        + "\n"
        + body
        + (
            f"\n\\section*{{Acknowledgment}}\n{spec.acknowledgments}\n"
            if spec.acknowledgments
            else ""
        )
        + _bib(spec, "IEEEtran", bib)
        + _appendix(appendix)
        + "\n\\end{document}\n"
    )


def _acm(spec: ArticleSpec, body: str, appendix: str, bib: str) -> str:
    authors = "\n".join(
        f"\\author{{{escape(a.name)}}}\n"
        + (f"\\orcid{{{escape(a.orcid)}}}\n" if a.orcid else "")
        + (f"\\email{{{escape(a.email)}}}\n" if a.email else "")
        + f"\\affiliation{{\\institution{{{escape(a.affiliation or 'Independent')}}}\\country{{}}}}"
        for a in spec.authors
    )
    return (
        _magic(spec)
        + "\\documentclass[sigconf]{acmart}\n"
        + "\\settopmatter{printacmref=false}\n"
        + "\\renewcommand\\footnotetextcopyrightpermission[1]{}\n"
        + "\\setcopyright{none}\n\\acmConference{}{}{}\n"
        + f"\n\\title{{{escape(spec.title)}}}\n{authors}\n\n"
        + "\\begin{document}\n"
        + (f"\\begin{{abstract}}\n{spec.abstract}\n\\end{{abstract}}\n" if spec.abstract else "")
        + (f"\\keywords{{{escape(', '.join(spec.keywords))}}}\n" if spec.keywords else "")
        + "\\maketitle\n\n"
        + body
        + (
            f"\n\\begin{{acks}}\n{spec.acknowledgments}\n\\end{{acks}}\n"
            if spec.acknowledgments
            else ""
        )
        + _bib(spec, "ACM-Reference-Format", bib)
        + _appendix(appendix)
        + "\n\\end{document}\n"
    )


def _springer(spec: ArticleSpec, body: str, appendix: str, bib: str) -> str:
    affiliations = []
    marks = []
    for author in spec.authors:
        key = author.affiliation or "Independent"
        if key not in affiliations:
            affiliations.append(key)
        marks.append(affiliations.index(key) + 1)
    names = " \\and ".join(
        f"{escape(a.name)}\\inst{{{mark}}}" + (f"\\orcidID{{{escape(a.orcid)}}}" if a.orcid else "")
        for a, mark in zip(spec.authors, marks, strict=True)
    )
    emails = {
        affiliations.index(a.affiliation or "Independent"): a.email for a in spec.authors if a.email
    }
    institutes = " \\and ".join(
        escape(name) + (f"\\\\ \\email{{{escape(emails[i])}}}" if i in emails else "")
        for i, name in enumerate(affiliations)
    )
    running = escape(spec.authors[0].name) + (" et al." if len(spec.authors) > 1 else "")
    return (
        _magic(spec)
        + "\\documentclass[runningheads]{llncs}\n"
        + _encoding(spec)
        + f"\\usepackage[{_babel(spec)}]{{babel}}\n"
        + _COMMON
        + _hyperref(spec)
        + f"\n\\title{{{escape(spec.title)}}}\n\\author{{{names}}}\n"
        + f"\\authorrunning{{{running}}}\n"
        + f"\\institute{{{institutes}}}\n\n"
        + "\\begin{document}\n\\maketitle\n\n"
        + (
            f"\\begin{{abstract}}\n{spec.abstract}\n"
            + (f"\n\\keywords{{{_keywords(spec, AND)}}}\n" if spec.keywords else "")
            + "\\end{abstract}\n"
            if spec.abstract
            else ""
        )
        + "\n"
        + body
        + (
            f"\n\\begin{{credits}}\n\\subsubsection{{\\ackname}} {spec.acknowledgments}\n"
            "\\end{credits}\n"
            if spec.acknowledgments
            else ""
        )
        + _bib(spec, "splncs04", bib)
        + _appendix(appendix)
        + "\n\\end{document}\n"
    )


def _elsevier(spec: ArticleSpec, body: str, appendix: str, bib: str) -> str:
    affiliations: list[str] = []
    author_lines = []
    for author in spec.authors:
        key = author.affiliation or "Independent"
        if key not in affiliations:
            affiliations.append(key)
        line = f"\\author[{affiliations.index(key) + 1}]{{{escape(author.name)}}}"
        if author.email:
            line += f"\n\\ead{{{escape(author.email)}}}"
        author_lines.append(line)
    affiliation_lines = "\n".join(
        f"\\affiliation[{i + 1}]{{organization={{{escape(name)}}}}}"
        for i, name in enumerate(affiliations)
    )
    keywords = (
        f"\\begin{{keyword}}\n{_keywords(spec, SEP)}\n\\end{{keyword}}\n" if spec.keywords else ""
    )
    return (
        _magic(spec)
        + "\\documentclass[preprint,12pt]{elsarticle}\n"
        + _encoding(spec)
        + f"\\usepackage[{_babel(spec)}]{{babel}}\n"
        + _COMMON
        + "\\usepackage{lineno}\n"
        + _hyperref(spec)
        + "\\begin{document}\n\\begin{frontmatter}\n"
        + f"\\title{{{escape(spec.title)}}}\n"
        + "\n".join(author_lines)
        + "\n"
        + affiliation_lines
        + "\n"
        + (f"\\begin{{abstract}}\n{spec.abstract}\n\\end{{abstract}}\n" if spec.abstract else "")
        + keywords
        + "\\end{frontmatter}\n\n"
        + body
        + (
            f"\n\\section*{{Acknowledgements}}\n{spec.acknowledgments}\n"
            if spec.acknowledgments
            else ""
        )
        + _bib(spec, "elsarticle-num", bib)
        + _appendix(appendix)
        + "\n\\end{document}\n"
    )


def _abnt(spec: ArticleSpec, body: str, appendix: str, bib: str) -> str:
    info = spec.abnt
    # \and only exists inside \maketitle; abnTeX2's cover sets \imprimirautor in a plain
    # centering block, where it breaks the build.
    author = " \\\\ ".join(escape(a.name) for a in spec.authors)
    institution = escape(
        str(info.get("institution") or (spec.authors[0].affiliation if spec.authors else ""))
    )
    abstract_en = spec.abstract_en or ""
    keywords_en = spec.keywords_en or []
    resumo = ""
    if spec.abstract:
        resumo = (
            "\\begin{resumo}\n"
            f"{spec.abstract}\n\n"
            + (
                f"\\textbf{{Palavras-chave}}: {escape('. '.join(spec.keywords))}.\n"
                if spec.keywords
                else ""
            )
            + "\\end{resumo}\n"
        )
    if abstract_en:
        resumo += (
            "\\begin{resumo}[Abstract]\n\\begin{otherlanguage*}{english}\n"
            f"{abstract_en}\n\n"
            + (f"\\textbf{{Keywords}}: {escape('. '.join(keywords_en))}.\n" if keywords_en else "")
            + "\\end{otherlanguage*}\n\\end{resumo}\n"
        )
    return (
        _magic(spec)
        + "\\documentclass[12pt,openright,oneside,a4paper,english,brazil]{abntex2}\n"
        + _encoding(spec)
        + "\\usepackage{indentfirst}\n\\usepackage{microtype}\n"
        + _COMMON
        + "\\usepackage[alf]{abntex2cite}\n"
        + f"\n\\titulo{{{escape(spec.title)}}}\n"
        + f"\\autor{{{author}}}\n"
        + f"\\local{{{escape(str(info.get('city', '')))}}}\n"
        + f"\\data{{{escape(str(info.get('year', spec.date)))}}}\n"
        + f"\\instituicao{{{institution}}}\n"
        + f"\\tipotrabalho{{{escape(str(info.get('type', 'Trabalho acadêmico')))}}}\n"
        + (f"\\orientador{{{escape(str(info['advisor']))}}}\n" if info.get("advisor") else "")
        + (f"\\coorientador{{{escape(str(info['coadvisor']))}}}\n" if info.get("coadvisor") else "")
        + f"\\preambulo{{{escape(str(info.get('preamble', '')))}}}\n"
        + "\n\\makeatletter\n"
        + "\\hypersetup{pdftitle={\\@title}, pdfauthor={\\@author}, hidelinks}\n"
        + "\\makeatother\n"
        + "\\setlength{\\parindent}{1.3cm}\n\\setlength{\\parskip}{0.2cm}\n"
        + "\\makeindex\n\n"
        + "\\begin{document}\n\\selectlanguage{brazil}\n\\frenchspacing\n"
        # abnTeX2 reads the token after \imprimirfolhaderosto as an argument: the blank line
        # (a \par) must be that token, or it swallows the next \begin and the build fails.
        + "\\imprimircapa\n\\imprimirfolhaderosto*\n\n"
        + resumo
        + "\\pdfbookmark[0]{\\contentsname}{toc}\n\\tableofcontents*\n\\cleardoublepage\n"
        + "\\textual\n\n"
        + body
        + (
            "\n\\chapter*{Agradecimentos}\n" + spec.acknowledgments + "\n"
            if spec.acknowledgments
            else ""
        )
        + "\n\\postextual\n"
        + (f"\\bibliography{{{bib}}}\n" if spec.has_bibliography else "")
        + (
            f"\n\\begin{{apendicesenv}}\n\\partapendices\n{appendix}\n\\end{{apendicesenv}}\n"
            if appendix.strip()
            else ""
        )
        + "\n\\end{document}\n"
    )
