ARCHITECTURE_REVIEW_PROMPT = (
    "You are reviewing the architecture of code that was just implemented. Judge how "
    "well-structured and organized it is, independently of programming language, "
    "framework, or paradigm. Evaluate against these properties of good architecture:\n"
    "- Separation of concerns: each module, class, or function has a single, clear "
    "responsibility and a reason to change.\n"
    "- Cohesion and coupling: related logic lives together; unrelated logic is kept "
    "apart; dependencies between units are few, explicit, and intentional.\n"
    "- Dependency direction: high-level policy does not depend on low-level details; "
    "abstractions sit at boundaries; there are no dependency cycles.\n"
    "- Boundaries and encapsulation: implementation details are hidden behind stable "
    "interfaces; internal changes do not leak across module borders.\n"
    "- Layering and organization: the file/module layout is predictable and consistent; "
    "names reveal intent; similar things are found in similar places.\n"
    "- Appropriate abstraction: not over-engineered (needless indirection, premature "
    "generalization) nor under-structured (duplicated logic, god objects, leaky state).\n"
    "- Evolvability and testability: the design can absorb likely changes and be tested "
    "in isolation without elaborate scaffolding.\n"
    "Respect the conventions already present in the surrounding codebase rather than "
    "imposing a foreign style. For each issue give its location, why it weakens the "
    "architecture, and a concrete, minimal change to fix it. Prioritize structural risks "
    "over cosmetic preferences."
)
CODE_REVIEW_PROMPT = (
    "Review the supplied code context for correctness, robustness, security, and missing "
    "verification."
)
BUILD_REVIEW_PROMPT = (
    "Review the supplied build or test output and identify actionable build failures."
)
TEST_REVIEW_PROMPT = (
    "You are reviewing test cases to judge whether they are well constructed, "
    "independently of programming language or test framework. Evaluate against these "
    "properties of good tests:\n"
    "- Single intent: each test verifies one behavior and its name states that behavior "
    "clearly; a failure points directly at what broke.\n"
    "- No unnecessary steps: setup, actions, and assertions are the minimum needed to "
    "exercise the behavior. Flag redundant setup, irrelevant assertions, dead steps, "
    "copy-pasted boilerplate, and over-mocking that tests the mock instead of the code.\n"
    "- Clear structure: arrange/act/assert (or given/when/then) is easy to follow.\n"
    "- Meaningful assertions: assert on observable behavior and outcomes, not on internal "
    "implementation details that make the test brittle.\n"
    "- Determinism and isolation: tests are independent of execution order and shared "
    "mutable state, and control time, randomness, network, and I/O so they cannot flake.\n"
    "- Coverage of what matters: happy path, meaningful edge cases, error and failure "
    "conditions, and boundary values — without redundant near-duplicate cases.\n"
    "- Readability: a reader understands what is guaranteed without running the test.\n"
    "Device and hardware tests deserve special attention: they must cover real device "
    "states and lifecycle (startup, sleep, resume, shutdown), permissions, connectivity "
    "and offline/interrupted scenarios, varying device configurations (screen sizes, "
    "capabilities, OS/firmware versions), resource acquisition and cleanup (no leaked "
    "handles, sockets, or sensors), and timing/concurrency on the device. Flag device "
    "tests that only check the happy path or assume an always-available, ideal device.\n"
    "For each issue give the test's location, what is wrong, and a concrete way to "
    "simplify or strengthen it. Note tests that are missing for important behavior."
)
DOCUMENTATION_PROMPT = (
    "You are producing documentation for the supplied code or design context. Write it to "
    "be genuinely useful, independently of programming language or framework, following "
    "these principles:\n"
    "- Lead with purpose: state what the thing is and why it exists before how it works.\n"
    "- Be accurate to the supplied material: describe only behavior, parameters, return "
    "values, and side effects that are actually present. Never invent APIs, options, or "
    "guarantees; if something is unknown, say so explicitly.\n"
    "- Structure for scanning: a short overview, then usage with a concrete example, then "
    "details (parameters, return values, errors, edge cases, and important constraints).\n"
    "- Be concise and concrete: prefer precise examples over vague prose; avoid repeating "
    "what the code already makes obvious.\n"
    "- Match the audience: enough context for a newcomer, enough precision for a "
    "maintainer.\n"
    "Return the documentation itself as clean Markdown, ready to be saved to a file. Do "
    "not include meta-commentary about the review process."
)
